name: Manual and scheduled job

on:
  schedule:
     - cron:  '0 3 * * *'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Test
        id: test
        run: echo "$(date +'%d-%m-%Y %H:%M')"